### ISSUE TITLE
cassandra node in `CrashLoopBackOff` 

### ISSUE THREAD

**Issue by schmurfy** [jaegertracing/helm-charts#108]
of the three cassandra nodes one is crashing continuously:

```
INFO  [main] 2020-05-19 15:06:04,423 StorageService.java:1478 - JOINING: Starting to bootstrap...
Exception (java.lang.RuntimeException) encountered during startup: A node required to move the data consistently is down (/10.4.3.44). If you wish to move the data from a potentially inconsistent replica, restart the node with -Dcassandra.consistent.rangemovement=false
java.lang.RuntimeException: A node required to move the data consistently is down (/10.4.3.44). If you wish to move the data from a potentially inconsistent replica, restart the node with -Dcassandra.consistent.rangemovement=false
  at org.apache.cassandra.dht.RangeStreamer.getAllRangesWithStrictSourcesFor(RangeStreamer.java:294)
  at org.apache.cassandra.dht.RangeStreamer.addRanges(RangeStreamer.java:177)
  at org.apache.cassandra.dht.BootStrapper.bootstrap(BootStrapper.java:87)
  at org.apache.cassandra.service.StorageService.bootstrap(StorageService.java:1530)
  at org.apache.cassandra.service.StorageService.joinTokenRing(StorageService.java:1024)
  at org.apache.cassandra.service.StorageService.initServer(StorageService.java:718)
  at org.apache.cassandra.service.StorageService.initServer(StorageService.java:652)
  at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:397)
  at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:630)
  at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:757)
ERROR [main] 2020-05-19 15:06:04,475 CassandraDaemon.java:774 - Exception encountered during startup
java.lang.RuntimeException: A node required to move the data consistently is down (/10.4.3.44). If you wish to move the data from a potentially inconsistent replica, restart the node with -Dcassandra.consistent.rangemovement=false
  at org.apache.cassandra.dht.RangeStreamer.getAllRangesWithStrictSourcesFor(RangeStreamer.java:294) ~[apache-cassandra-3.11.6.jar:3.11.6]
  at org.apache.cassandra.dht.RangeStreamer.addRanges(RangeStreamer.java:177) ~[apache-cassandra-3.11.6.jar:3.11.6]
  at org.apache.cassandra.dht.BootStrapper.bootstrap(BootStrapper.java:87) ~[apache-cassandra-3.11.6.jar:3.11.6]
  at org.apache.cassandra.service.StorageService.bootstrap(StorageService.java:1530) ~[apache-cassandra-3.11.6.jar:3.11.6]
  at org.apache.cassandra.service.StorageService.joinTokenRing(StorageService.java:1024) ~[apache-cassandra-3.11.6.jar:3.11.6]
  at org.apache.cassandra.service.StorageService.initServer(StorageService.java:718) ~[apache-cassandra-3.11.6.jar:3.11.6]
  at org.apache.cassandra.service.StorageService.initServer(StorageService.java:652) ~[apache-cassandra-3.11.6.jar:3.11.6]
  at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:397) [apache-cassandra-3.11.6.jar:3.11.6]
  at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:630) [apache-cassandra-3.11.6.jar:3.11.6]
  at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:757) [apache-cassandra-3.11.6.jar:3.11.6]
INFO  [StorageServiceShutdownHook] 2020-05-19 15:06:04,487 HintsService.java:209 - Paused hints dispatch
WARN  [StorageServiceShutdownHook] 2020-05-19 15:06:04,490 Gossiper.java:1655 - No local state, state is in silent shutdown, or node hasn't joined, not announcing shutdown
INFO  [StorageServiceShutdownHook] 2020-05-19 15:06:04,491 MessagingService.java:985 - Waiting for messaging service to quiesce
INFO  [ACCEPT-/10.4.3.79] 2020-05-19 15:06:04,491 MessagingService.java:1346 - MessagingService has terminated the accept() thread
INFO  [StorageServiceShutdownHook] 2020-05-19 15:06:04,987 HintsService.java:209 - Paused hints dispatch
```

**Comment by naseemkullah** [comment]
Sorry @schmurfy, this one falls out of scope here, I would suggest opening an issue with the cassandra chart itself.

Also this may be of interest (a comparison of cassandra and elasticsearch as jaeger backends from one of the jaeger maintainers): https://github.com/jaegertracing/documentation/pull/406/files

**Comment by naseemkullah** [comment]
I am no Cassandra expert, but will leave this open in case someone else can help!

**Comment by schmurfy** [comment]
Thanks, I was wondering about es, I will have a look.
